feat: добавление режиссеров и нового функционала
Sucheit/java-filmorate pull request #16
Opened 2023-04-28 13:05 UTC by BezuglovMikhail

Добавление режиссера и функционала связанного с ним.

2023-04-28 16:35 UTC, Sucheit requested changes

2023-04-28 16:35 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        if (sortBy.equals("year")) {
обработку логики нужно перенести в сервис, разбив на 2 метода в дао

2023-04-28 16:35 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                throw new FilmNotFoundException("Фильмы с заданной сортировкой: " + sortBy + " не найдены");
если ничего запрос не нашел вернуть должен пустой лист

2023-04-28 16:58 UTC, BezuglovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                throw new FilmNotFoundException("Фильмы с заданной сортировкой: " + sortBy + " не найдены");
Я сначала так сделал, но тогда последний тест в постмане не прохожу. Судя по тесту должна быть ошибка.

2023-04-28 17:08 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                throw new FilmNotFoundException("Фильмы с заданной сортировкой: " + sortBy + " не найдены");
там же удаляется режисер вначале, потом запрос делается, нужно проверить id режисера на существование в сервисе и все

2023-04-28 17:10 UTC, Sucheit requested changes

2023-04-28 17:10 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getFilmsByDirectorId(Long directorId, String sortBy) {
здесь нужна проверка directorid на сущетсвование

2023-04-28 17:16 UTC, BezuglovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                throw new FilmNotFoundException("Фильмы с заданной сортировкой: " + sortBy + " не найдены");
Вот тест: {{baseUrl}}/films/director/:director?sortBy=likes

pm.test("Status code is 404", function () {
    pm.response.to.have.status(404);
});

2023-04-28 17:19 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                throw new FilmNotFoundException("Фильмы с заданной сортировкой: " + sortBy + " не найдены");
все верно 404 not found только не фильмы а удаленного режисера

2023-04-28 17:36 UTC, BezuglovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        if (sortBy.equals("year")) {
Исправил.

2023-04-28 17:49 UTC, BezuglovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                throw new FilmNotFoundException("Фильмы с заданной сортировкой: " + sortBy + " не найдены");
Теперь понял, исправил.

2023-04-28 17:53 UTC, BezuglovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> getFilmsByDirectorId(Long directorId, String sortBy) {
Исправил.

2023-04-28 19:36 UTC, Sucheit requested changes

2023-04-28 19:36 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +            throw new FilmNotFoundException("Фильмы с заданной сортировкой по году не найдены");
зачем это исключение? если нет фильмов должен возвращаться пустой список

2023-04-29 03:16 UTC, BezuglovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +            throw new FilmNotFoundException("Фильмы с заданной сортировкой по году не найдены");
исправил.

2023-04-29 04:38 UTC, Sucheit approved these changes

2023-04-29 05:14 UTC, Zel-ik approved these changes

2023-04-29 10:06 UTC, merged