добавление функционала поиск
Sucheit/java-filmorate pull request #19
Opened 2023-04-29 18:16 UTC by mitri4hock

2023-04-29 20:41 UTC, Sucheit requested changes

2023-04-29 20:41 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    public List<Film> searchFilms(String query, String by) {
лучше вынести логику в сервис и разбить на 3 метода в дао

2023-04-29 20:41 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (query.isBlank() || by.isBlank()) {
не нужная проверка, в контроллере @requestparam по дефолту обязательны

2023-04-29 20:41 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.length() < 9) {
можно лучше: вместо вложенных if else сделать через switch

2023-05-01 09:49 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (query.isBlank() || by.isBlank()) {
по дефолту да- но может придти запрос с фронта с неправильными параметрами. Бланк- в том числе, проверяет на "" пустую строку

2023-05-01 09:52 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    public List<Film> searchFilms(String query, String by) {
БД работает сильно быстрее rest приложений. Так же- она, обычно, оптимизирована под такие запросы. Да и нагрузка от одного запроса с джойнами на БД будет меньше, чем на 3 маленьких запроса.

2023-05-01 10:44 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.length() < 9) {
не совсем понял... Там двойные условия и через case вроде как не прогнать. ПС-посмотри, пожалуйста последний коммит

2023-05-01 11:03 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    public List<Film> searchFilms(String query, String by) {
это про другое, в данном случае нету каких то сложных запросов, которых я прошу разбивать, у тебя в одном методе дао логика выбора запросов, и эту логику выбора лучше вынести в сервис

2023-05-01 11:07 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.length() < 9) {
в case можно if сделать и тогда без else можно обойтись

2023-05-01 11:08 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (query.isBlank() || by.isBlank()) {
ок, оставь

2023-05-01 17:47 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    public List<Film> searchFilms(String query, String by) {
принято. Исправлено

2023-05-01 17:47 UTC, mitri4hock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.length() < 9) {
принято. Исправлено

2023-05-01 18:12 UTC, Sucheit approved these changes

2023-05-02 07:22 UTC, BezuglovMikhail approved these changes

2023-05-02 09:02 UTC, merged