Sprint 12 Групповой проект
Sucheit/java-filmorate pull request #24
Opened 2023-05-02 15:30 UTC by Sucheit

2023-05-03 14:06 UTC, mikita95 requested changes
Все сделано отлично :) Выбран интересный список фич для реализации. Нужно поправить лишь пару моментов.

2023-05-03 14:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorDao.java
> +    void deleteDirector(Long directorId);
Здесь лучше принимать примитивный тип, так точно null не передать будет

2023-05-03 18:52 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorDao.java
> +    void deleteDirector(Long directorId);
исправлено

2023-05-03 18:52 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        List<Film> films;
исправлено

2023-05-03 18:52 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        List<Film> films;
исправлено

2023-05-03 18:53 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +            deleteFilmDirectors(film.getId());
исправлено

2023-05-03 18:53 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (sortBy.equals("year")) {
исправлено

2023-05-03 18:54 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        String sqlReviews = "UPDATE \"reviews\" SET USEFUL = ((SELECT USEFUL FROM \"reviews\"" +
исправлено

2023-05-03 18:54 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            if (review.getIsPositive() == null) throw new IncorrectParameterException("isPositive is null");
исправлено

2023-05-03 19:18 UTC, Sucheit commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        switch (by) {
не получается значение с запятой через enum задать

2023-05-04 19:08 UTC, mikita95 reviewed
Все отлично :) Можно мержить пул-реквест.

2023-05-04 20:01 UTC, merged